version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai-game-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepassword
      POSTGRES_DB: ai_guessing_game
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameuser -d ai_guessing_game"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 